[workspace]
members = [
    "crates/gluj-bench-core",
    "crates/gluj-bench-cpu",
    "crates/gluj-bench-gpu",
    "crates/gluj-bench-worker",
    "crates/gluj-bench-ui",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/githubdood21/Gluj-Bench"
homepage = "https://github.com/githubdood21/Gluj-Bench"
license = "MIT"

[workspace.dependencies]
ash = "0.38"
slint = "1.17.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.39"
thiserror = "2"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
] }

[profile.dev.package.gluj-bench-cpu]
opt-level = 3

[profile.dev.package.gluj-bench-gpu]
opt-level = 3

[profile.dev.package.miniz_oxide]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
