[package]
name = "gluj-bench-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
gluj-bench-core = { path = "../gluj-bench-core" }
serde_json.workspace = true
serde.workspace = true
slint = { workspace = true, features = ["unstable-winit-030"] }

[build-dependencies]
embed-resource = "3.0.11"
slint-build = "1.17.1"
