[package]
name = "gluj-bench-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[dependencies]
eframe.workspace = true
gluj-bench-core = { path = "../gluj-bench-core" }
serde_json.workspace = true
