[package]
name = "gluj-bench-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[dependencies]
ash.workspace = true
gluj-bench-core = { path = "../gluj-bench-core" }
sysinfo.workspace = true
